steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
            'build',
            '-t', 'gcr.io/$PROJECT_ID/satak-image',
            '.'
        ]
- name: 'gcr.io/cloud-builders/kubectl'
  args: [
          'set',
          'image',
          'deployment/satak-service',
          'satak-service=gcr.io/$PROJECT_ID/satak-image',
          '-n',
          '${_NAMESPACE}'
        ]
  env: [
        'CLOUDSDK_COMPUTE_ZONE=${_COMPUTE_ZONE}',
        'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'
       ]
images:
- 'gcr.io/$PROJECT_ID/satak-image'
tags:
- "test"
- "tag2"