steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'gcr.io/$PROJECT_ID/satak-image']
- name: 'gcr.io/cloud-builders/docker'
  args: [
            'build',
            '--cache-from',
            'gcr.io/$PROJECT_ID/satak-image',
            '-t', 'gcr.io/$PROJECT_ID/satak-image',
            '.'
        ]
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/satak-image"]
- name: 'gcr.io/cloud-builders/kubectl'
  args: [
          'set',
          'image',
          'deployment',
          'satak-deployment',
          'satak-container=gcr.io/$PROJECT_ID/satak-image:latest'
        ]
  env: [
        'CLOUDSDK_COMPUTE_ZONE=${_COMPUTE_ZONE}',
        'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'
       ]