steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
            'build',
            '-t', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:staging-$REVISION_ID',
            '.'
        ]
  env: [
        'CLOUDSDK_COMPUTE_ZONE=${_COMPUTE_ZONE}',
        'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'
       ]
images:
- 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:staging-$REVISION_ID'
tags:
- "staging"