steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
            'build',
            '-t', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$TAG_NAME',
            '.'
        ]
- name: 'gcr.io/cloud-builders/kubectl'
  args: [
          'set',
          'image',
          'deployment/${_DEPLOYMENT_NAME}',
          '${_DEPLOYMENT_NAME}=gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$TAG_NAME',
          '-n',
          '${_NAMESPACE}'
        ]
  env: [
        'CLOUDSDK_COMPUTE_ZONE=${_COMPUTE_ZONE}',
        'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'
       ]
images:
- 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$TAG_NAME'
tags:
- "production"
- "$TAG_NAME"