steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
            'build',
            '-t', 'gcr.io/$PROJECT_ID/satak-image:latest',
            '.'
        ]
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/satak-image:latest"]
- name: 'eu.gcr.io/cloud-builders/kubectl'
  args: [
          'apply',
          'image',
          'deployment/satak-service',
          'satak-service=gcr.io/$PROJECT_ID/satak-image:latest'
        ]
  env: [
        'CLOUDSDK_COMPUTE_ZONE=${_COMPUTE_ZONE}',
        'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'
       ]