steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
            'build',
            '-t', 'gcr.io/$PROJECT_ID/satak-image:$TAG_NAME',
            '.'
        ]
- name: 'gcr.io/cloud-builders/kubectl'
  args: [
          'set',
          'image',
          'deployment/satak-service',
          'satak-service=gcr.io/$PROJECT_ID/satak-image:$TAG_NAME',
          '-n',
          '${_NAMESPACE}'
        ]
  env: [
        'CLOUDSDK_COMPUTE_ZONE=${_COMPUTE_ZONE}',
        'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'
       ]
substitutions:
    TAG_NAME: $REVISION_ID # default value
images:
- 'gcr.io/$PROJECT_ID/satak-image:$TAG_NAME'
tags:
- "$TAG_NAME"
- "$REVISION_ID"