apiVersion: v1
kind: Service
metadata:
  name: satak-service
  namespace: default
spec:
  ports:
  - port: 80
    name: http
    targetPort: 8080
    protocol: TCP
  selector:
    app: satak-service
  type: LoadBalancer